# Generated by Django 4.1.5 on 2023-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleIntegration',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('is_active', models.BooleanField(db_column='cs_active', default=True)),
                ('site', models.CharField(choices=[('1', 'Loja Matriz'), ('2', 'Loja 2'), ('3', 'Loja 3')], db_column='cs_type', default='1', max_length=1, verbose_name='Site')),
                ('payment_type', models.CharField(db_column='cs_payment', max_length=255, verbose_name='Payment type')),
                ('order_date', models.DateField(db_column='dt_order', verbose_name='Order date')),
                ('sale_date', models.DateField(db_column='dt_sale', verbose_name='Sale date')),
                ('sale_price', models.DecimalField(db_column='nb_sale_price', decimal_places=2, max_digits=10, verbose_name='Sale price')),
                ('vendor_name', models.CharField(db_column='tx_vendor_name', max_length=256, verbose_name='Vendor name')),
            ],
            options={
                'verbose_name': 'IntegrationSale',
                'verbose_name_plural': 'IntegrationSales',
                'db_table': 'shift',
                'managed': True,
            },
        ),
    ]
