# Generated by Django 4.1.5 on 2023-04-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofifa_id', models.IntegerField(db_column='nb_sofifa_id', verbose_name='Sofifa id')),
                ('player_url', models.CharField(db_column='tx_player_url', max_length=128, verbose_name='Player url')),
                ('short_name', models.CharField(db_column='tx_short_name', max_length=64, verbose_name='Short name')),
                ('long_name', models.CharField(db_column='tx_long_name', max_length=64, verbose_name='Long name')),
                ('age', models.IntegerField(db_column='nb_agr', verbose_name='Age')),
                ('nationality', models.CharField(db_column='tx_nationality', max_length=64, verbose_name='Nationality')),
                ('club_name', models.CharField(db_column='tx_club_name', max_length=64, verbose_name='Club name')),
                ('league_name', models.CharField(db_column='tx_league_name', max_length=64, verbose_name='League name')),
                ('league_rank', models.IntegerField(db_column='nb_league_rank', verbose_name='League rank')),
                ('overall', models.IntegerField(db_column='nb_overall', verbose_name='Overall')),
                ('potential', models.IntegerField(db_column='nb_potential', verbose_name='Potential')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='SaleIntegration',
        ),
    ]
