# Generated by Django 4.1.5 on 2023-04-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_delete_saleintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='league_rank',
        ),
    ]
